Repository metaopt/torchopt, pull requests merged in 2022-10, with the labels that each got.

#95 fix(examples): align results of distributed examples
  CHANGELOG.md
  README.md
  conda-recipe.yaml
  docs/source/examples/MAML.rst
  examples/L2R/l2r.py
  examples/LOLA/helper/agent.py
  examples/LOLA/lola_dice.py
  examples/distributed/few-shot/maml-accs.png
  examples/distributed/few-shot/maml_omniglot.py
  examples/distributed/few-shot/maml_omniglot_local_loader.py
  examples/few-shot/maml-accs.png
  examples/few-shot/maml_omniglot.py
  pyproject.toml
  tests/requirements.txt
  torchopt/distributed/api.py
  torchopt/distributed/autograd.py
  torchopt/optim/base.py
  torchopt/optim/meta/base.py
  torchopt/transform.py
  torchopt/utils.py
  tutorials/3_Meta_Optimizer.ipynb
Labels: bug, upstream, pytorch, example / tutorial

#93 feat(zero_order): implemented the zero order feature
  .pylintrc
  CHANGELOG.md
  pyproject.toml
  torchopt/__init__.py
  torchopt/accelerated_op/adam_op.py
  torchopt/alias.py
  torchopt/base.py
  torchopt/distributed/api.py
  torchopt/implicit_diff.py
  torchopt/linalg.py
  torchopt/optim/base.py
  torchopt/optim/func/base.py
  torchopt/optim/meta/base.py
  torchopt/transform.py
  torchopt/typing.py
  torchopt/utils.py
  torchopt/zero_order_diff.py
Labels: enhancement, feature

#103 deps: bump optree to 0.3.0
  .github/workflows/build.yml
  .github/workflows/set_cibw_build.py
  .github/workflows/tests.yml
  Makefile
  docs/source/developer/contributing.rst
  pyproject.toml
  requirements.txt
  tests/helpers.py
  tests/test_alias.py
  tests/test_schedule.py
  torchopt/alias/utils.py
  torchopt/base.py
  torchopt/clip.py
  torchopt/combine.py
  torchopt/diff/implicit/decorator.py
  torchopt/diff/zero_order.py
  torchopt/distributed/api.py
  torchopt/hook.py
  torchopt/linalg/cg.py
  torchopt/optim/base.py
  torchopt/optim/func/base.py
  torchopt/optim/meta/base.py
  torchopt/pytree.py
  torchopt/transform/add_decayed_weights.py
  torchopt/transform/scale.py
  torchopt/transform/scale_by_adam.py
  torchopt/transform/scale_by_rms.py
  torchopt/transform/scale_by_schedule.py
  torchopt/transform/scale_by_stddev.py
  torchopt/transform/trace.py
  torchopt/transform/utils.py
  torchopt/typing.py
Labels: upstream, dependencies

#104 deps: bump PyTorch version to 1.13
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  Dockerfile
  README.md
  conda-recipe.yaml
  docs/conda-recipe.yaml
  docs/requirements.txt
  docs/source/developer/contributing.rst
  examples/requirements.txt
  pyproject.toml
  requirements.txt
  tests/requirements.txt
  tests/test_alias.py
  tests/test_clip.py
  tests/test_optim.py
  tutorials/requirements.txt
Labels: upstream, pytorch, functorch, dependencies
