Repository metaopt/torchopt, pull requests merged in 2022-08, with the labels that each got.

#45 feat(workflows): cibuildwheel integration
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  .readthedocs.yaml
  CHANGELOG.md
  CMakeLists.txt
  README.md
  docs/source/developer/contributing.rst
  docs/source/spelling_wordlist.txt
  pyproject.toml
  tests/requirements.txt
Labels: enhancement

#53 fix(CMakeLists.txt): fix CUDA build for accelerated OP
  CHANGELOG.md
  CMakeLists.txt
  src/adam_op/adam_op.cpp
Labels: bug

#58 fix(transform): fix momentum trace
  .gitignore
  CHANGELOG.md
  torchopt/_src/alias.py
  torchopt/_src/clip.py
  torchopt/_src/hook.py
  torchopt/_src/optimizer/adam.py
  torchopt/_src/optimizer/base.py
  torchopt/_src/optimizer/meta/adam.py
  torchopt/_src/optimizer/meta/base.py
  torchopt/_src/optimizer/meta/rmsprop.py
  torchopt/_src/optimizer/meta/sgd.py
  torchopt/_src/optimizer/rmsprop.py
  torchopt/_src/schedule.py
  torchopt/_src/transform.py
  torchopt/_src/update.py
  torchopt/_src/utils.py
  torchopt/_src/visual.py
Labels: bug

#32 Examples of parallel training on one GPU using functorch.vmap with torchopt
  CHANGELOG.md
  examples/FuncTorch/parallel_train_torchopt.py
  torchopt/_src/transform.py
Labels: enhancement, functorch, example / tutorial

#55 test: refactor tests using `pytest.mark.parametrize`
  .github/workflows/tests.yml
  CHANGELOG.md
  Makefile
  docs/conda-recipe.yaml
  docs/requirements.txt
  pyproject.toml
  tests/conftest.py
  tests/helpers.py
  tests/high_level/test_high_level_inplace.py
  tests/low_level/test_low_level.py
  tests/requirements.txt
  tests/test_clip.py
  tests/test_schedule.py
  tests/unit/high_level/test_high_level_inplace.py
  tests/unit/low_level/test_low_level_inplace.py
  tests/unit/test_clip.py
  tests/unit/test_schedule.py
  torchopt/_src/alias.py
  torchopt/_src/base.py
  torchopt/_src/combine.py
  torchopt/_src/hook.py
  torchopt/_src/optimizer/base.py
  torchopt/_src/optimizer/meta/base.py
  torchopt/_src/optimizer/sgd.py
  torchopt/_src/transform.py
  torchopt/_src/utils.py
Labels: bug, enhancement

#65 refactor: align argument names with PyTorch
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  .gitignore
  CHANGELOG.md
  Dockerfile
  tests/helpers.py
  tests/test_alias.py
  tests/test_clip.py
  tests/test_optimizer.py
  torchopt/__init__.py
  torchopt/_src/accelerated_op/adam_op/adam_op.py
  torchopt/_src/alias.py
  torchopt/_src/base.py
  torchopt/_src/clip.py
  torchopt/_src/combine.py
  torchopt/_src/hook.py
  torchopt/_src/optimizer/__init__.py
  torchopt/_src/optimizer/adam.py
  torchopt/_src/optimizer/base.py
  torchopt/_src/optimizer/meta/__init__.py
  torchopt/_src/optimizer/meta/adam.py
  torchopt/_src/optimizer/meta/base.py
  torchopt/_src/optimizer/meta/rmsprop.py
  torchopt/_src/optimizer/meta/sgd.py
  torchopt/_src/optimizer/rmsprop.py
  torchopt/_src/optimizer/sgd.py
  torchopt/_src/transform.py
  torchopt/_src/typing.py
  torchopt/_src/update.py
Labels: pytorch
