Repository metaopt/torchopt, pull requests merged in 2022-12, with the labels that each got.

#111 feat(diff/zero_order): add new parameter `num_samples`
  docs/source/spelling_wordlist.txt
  torchopt/diff/zero_order/__init__.py
  torchopt/diff/zero_order/decorator.py
  torchopt/typing.py
Labels: enhancement, feature

#112 perf(acc_op): further acceleration with CUDA unroll
  CHANGELOG.md
  src/adam_op/adam_op_impl_cpu.cpp
  src/adam_op/adam_op_impl_cuda.cu
Labels: enhancement, cxx / cuda

#126 style: rephrase docstrings
  torchopt/accelerated_op/adam_op.py
  torchopt/alias/adam.py
  torchopt/alias/adamw.py
  torchopt/alias/rmsprop.py
  torchopt/alias/sgd.py
  torchopt/alias/utils.py
  torchopt/base.py
  torchopt/clip.py
  torchopt/combine.py
  torchopt/diff/implicit/decorator.py
  torchopt/diff/implicit/nn/module.py
  torchopt/diff/zero_order/decorator.py
  torchopt/distributed/api.py
  torchopt/distributed/autograd.py
  torchopt/distributed/world.py
  torchopt/hook.py
  torchopt/linalg/ns.py
  torchopt/linalg/utils.py
  torchopt/linear_solve/cg.py
  torchopt/linear_solve/inv.py
  torchopt/linear_solve/normal_cg.py
  torchopt/linear_solve/utils.py
  torchopt/nn/module.py
  torchopt/optim/adam.py
  torchopt/optim/adamw.py
  torchopt/optim/base.py
  torchopt/optim/func/base.py
  torchopt/optim/meta/adam.py
  torchopt/optim/meta/adamw.py
  torchopt/optim/meta/base.py
  torchopt/optim/meta/rmsprop.py
  torchopt/optim/meta/sgd.py
  torchopt/optim/rmsprop.py
  torchopt/optim/sgd.py
  torchopt/pytree.py
  torchopt/schedule/polynomial.py
  torchopt/transform/add_decayed_weights.py
  torchopt/transform/nan_to_num.py
  torchopt/transform/scale_by_schedule.py
  torchopt/transform/trace.py
  torchopt/transform/utils.py
  torchopt/typing.py
  torchopt/update.py
  torchopt/visual.py
Labels: documentation
