Repository metaopt/torchopt, pull requests merged in 2023-02, with the labels that each got.

#127 docs: refactor documentation
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  CHANGELOG.md
  LICENSE
  Makefile
  README.md
  conda-recipe-minimal.yaml
  conda-recipe.yaml
  docs/conda-recipe.yaml
  docs/source/_static/images/explicit-gradient.png
  docs/source/_static/images/implicit-gradient.png
  docs/source/_static/images/visualization-fig1.svg
  docs/source/_static/images/visualization-fig2.svg
  docs/source/_static/images/visualization-fig3.svg
  docs/source/_static/images/zero-order.png
  docs/source/api/api.rst
  docs/source/basics/basics.rst
  docs/source/conf.py
  docs/source/developer/contributing.rst
  docs/source/developer/contributor.rst
  docs/source/distributed/distributed.rst
  docs/source/explicit_diff/explicit_diff.rst
  docs/source/implicit_diff/implicit_diff.rst
  docs/source/index.rst
  docs/source/optimizer/optim.rst
  docs/source/spelling_wordlist.txt
  docs/source/visualization/visualization.rst
  docs/source/zero_order_diff/zero_order_diff.rst
  tutorials/1_Functional_Optimizer.ipynb
  tutorials/2_Visualization.ipynb
  tutorials/3_Meta_Optimizer.ipynb
  tutorials/5_Implicit_Differentiation.ipynb
  tutorials/6_Zero_Order_Differentiation.ipynb
Labels: documentation

#133 refactor(workflows): rewrite setup CUDA Toolkit logic
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  CHANGELOG.md
Labels: enhancement, cxx / cuda, dependencies

#134 fix(Dockerfile): fix missing versioned packages
  Dockerfile
  Makefile
Labels: bug, dependencies

#138 feat: add flake8 plugins and enable pre-commit hook
  .flake8
  .pre-commit-config.yaml
  Makefile
  conda-recipe.yaml
  pyproject.toml
  setup.py
  tests/requirements.txt
  torchopt/_C/adam_op.pyi
  torchopt/diff/implicit/decorator.py
  torchopt/diff/zero_order/decorator.py
  torchopt/diff/zero_order/nn/module.py
  torchopt/distributed/__init__.py
  torchopt/distributed/autograd.py
  torchopt/linalg/ns.py
  torchopt/typing.py
Labels: enhancement

#140 test(workflows): enable tests on Windows
  .github/workflows/tests.yml
  CHANGELOG.md
  pyproject.toml
  tests/requirements.txt
  tests/test_implicit.py
Labels: enhancement, upstream, jax, dependencies
