Repository metaopt/torchopt, pull requests merged in 2023-03, with the labels that each got.

#145 fix: fix transpose empty iterable with `zip(*nested)` in transformations
  CHANGELOG.md
  codecov.yml
  tests/.coveragerc
  tests/test_alias.py
  tests/test_implicit.py
  tests/test_nn.py
  tests/test_zero_order.py
  torchopt/base.py
  torchopt/diff/implicit/nn/module.py
  torchopt/diff/zero_order/nn/module.py
  torchopt/transform/scale_by_adam.py
  torchopt/typing.py
  torchopt/utils.py
Labels: bug, better errors

#143 docs: add more details on implicit differentiation
  CHANGELOG.md
  docs/source/implicit_diff/implicit_diff.rst
Labels: documentation

#149 fix: fix CI failure for PyTorch 2.0
  conda-recipe.yaml
  pyproject.toml
  torchopt/optim/base.py
  torchopt/utils.py
Labels: upstream, pytorch
